name: Release, build and publish Mosquitto with Http Authorization Images
on:
  workflow_dispatch:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
    inputs:
      tag:
        description: Tag name to build and publish
        type: string
        required: true
    
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ inputs.tag }}
          release_name: Release ${{ inputs.tag }}
          body: |
            Changes in this Release
          draft: false
          prerelease: false  

  build-and-publish:
    name: Build and publish docker image
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code tag ${{ inputs.tag }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: sjexpos/mosquitto-http-auth:${{ inputs.tag }}
